### ISSUE TITLE
Change default output to reference file name

### ISSUE THREAD

**Issue by aztecrabbit** [smacke/ffsubsync#112]
Hi,

I think it's better to replace the default output file with a reference file name, for example:

Reference = `movie.mkv`
Output = `movie.srt` or `movie.ffsubsync.srt`

**Comment by smacke** [comment]
I'm not comfortable with this because we could end up overwriting the unsynced file name if it is named the same thing. I guess the option `movie.ffsubsync.srt` handles this to some extent. Overall I prefer to keep things explicit; if we introduce a magic file name it might be confusing. Going to close for now but happy to reopen if there's a compelling counterargument.
