### ISSUE TITLE
--vad=auditok not working

### ISSUE THREAD

**Issue by Rickexe** [smacke/ffsubsync#125]
Hello,

My subtitles were out of sync so I tried the command --vad=auditok. It doesn't seem to work. I get this error. Am I missing an argument? 

This is the command I ran: 

ffsubsync "example.mkv" -i "example.en.srt" -o "example.en.srt" --max-offset-seconds=600 --vad=auditok

![image](https://user-images.githubusercontent.com/48714886/114579002-bc5d2c80-9c7d-11eb-8b61-90ef8be64fd4.png)

**Comment by smacke** [comment]
Hi @Rickexe, thanks for filing an issue. It looks like the most recent version of auditok introduced some API inconsistencies. I went ahead and pushed a fix; if you run
```
pip install --upgrade ffsubsync
```
it should hopefully work (that is, the command shouldn't fail, but the sync is less certain). Please let me know if the command still fails after upgrading; if so I can investigate some more, otherwise I'll close this out.

**Comment by Rickexe** [comment]
Thank you. The command is working.

**Comment by smacke** [comment]
Fantastic! Thanks for the update. I'll close this out in that case.
