### ISSUE TITLE
Suppressing output because offset 8.49 was less than suppression threshold 0.5 ?

### ISSUE THREAD

**Issue by MartenBE** [smacke/ffsubsync#175]
```
INFO     offset seconds: 8.490
INFO     framerate scale factor: 0.986
WARNING  suppressing output because offset 8.49 was less than suppression threshold 0.5
```

The output is surpressed while 8.49 is in fact **_greater_** than threshold 0.5. I think it has something to do with the scaling factor not being 1?

```
if suppress_output_thresh is None or (
    scale_step.scale_factor == 1.0
    and offset_seconds >= suppress_output_thresh
):
    logger.info("writing output to {}".format(srtout or "stdout"))
    out_subs.write_file(srtout)
else:
    logger.warning(
        "suppressing output because offset %s was less than suppression threshold %s",
        offset_seconds,
        args.suppress_output_if_offset_less_than,
    )
```

https://github.com/smacke/ffsubsync/blob/8bcbd949e72285fee011fd39c46efc825561e8de/ffsubsync/ffsubsync.py#L205

Commandline options used: `ffsubsync --srtin <sub> --gss --overwrite-input --suppress-output-if-offset-less-than 0.5 <video>`

**Comment by smacke** [comment]
Looks like a bug to me, or at the very least extremely misleading. It's because of the check on the scale factor -- my guess is that the intention here is to only allow suppression when the scale factor is 1.0, since otherwise it's hard to tell what the "true" offset was. In any case I don't think that check should be present. Will push a fix shortly; I'm on vacation right now so a release will take a bit longer.

**Comment by smacke** [comment]
Just a heads up, I cut a release today with this bugfix -- behavior should be better if you do
```
pip install --upgrade ffsubsync
```

Thanks again for the initial report @MartenBE !

**Comment by MartenBE** [comment]
Thank you for fixing this issue and for the creation of this software!
